# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('departament', models.CharField(max_length=200, verbose_name='departament')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'employees',
                'ordering': ('-created_at',),
            },
        ),
    ]
