# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20170617_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='departament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
